name = "tuziyo"
pages_build_output_dir = "./build/client"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_APP_ORIGIN = "https://tuziyo.com"
BASE_URL = "/blog/"
BUN_VERSION = "latest"